export const FiveDie = () => {
  return (
    <svg width="100" height="100" className="bg-white">
      <rect
        x="1"
        y="1"
        width="100"
        height="100"
        stroke="black"
        fill="transparent"
        strokeWidth="2"
      />
      <circle
        cx="20"
        cy="20"
        r="10"
        stroke="black"
        fill="black"
        strokeWidth="2"
      />
      <circle
        cx="20"
        cy="80"
        r="10"
        stroke="black"
        fill="black"
        strokeWidth="2"
      />
      <circle
        cx="80"
        cy="20"
        r="10"
        stroke="black"
        fill="black"
        strokeWidth="2"
      />
      <circle
        cx="80"
        cy="80"
        r="10"
        stroke="black"
        fill="black"
        strokeWidth="2"
      />
      <circle
        cx="50"
        cy="50"
        r="10"
        stroke="black"
        fill="black"
        strokeWidth="2"
      />
    </svg>
  );
};
