import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import clsx from 'clsx'
import { ToastProvider } from './context/ToastProvider'
import { UserProvider } from './context/UserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Craps',
  description: 'Generated by create next app',
}

// eslint-disable-next-line space-before-function-paren
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx('h-full', inter.className)}>
        <ToastProvider>
          <UserProvider>{children}</UserProvider>
        </ToastProvider>
      </body>
    </html>
  )
}
